### ISSUE TITLE
TLS Errors

### ISSUE THREAD

**Issue by joelbyler** [smythey21/google-geocoding-api-elixir#8]
Recently started receiving these errors when attempting to use `all_info` function

```
** (HTTPoison.Error) {:tls_alert, 'unknown ca'}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (google_geocoding_api) lib/google_geocoding_api.ex:7: GoogleGeocodingApi.all_info/2
```

**Comment by smythey21** [comment]
Hey @joelbyler thanks for reporting. Are you able to make the same request with your api key with something like curl? 

```
curl https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=YOUR_API_KEY
```

**Comment by joelbyler** [comment]
Good question, I’m afk currently but can try later. This was working
previously, I’m not sure when it stopped working though.

**Comment by joelbyler** [comment]
@smythey21 yeah I can try that url with a web browser (chrome) and it works well but trying to just curl like you have it results in the following: 
```
{
   "error_message" : "You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account",
   "results" : [],
   "status" : "REQUEST_DENIED"
}
```

**Comment by smythey21** [comment]
Oh that's because you have to replace `YOUR_API_KEY` in the url with your actual api key
